// <auto-generated />
using System;
using Catalogo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalogo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogoDbContext))]
    [Migration("20250929174422_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Catalogo.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("IconeUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PrecoCentavos")
                        .HasColumnType("int");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f5a8c9e-b781-4af1-9bfb-7a3d67cfec21"),
                            Ativo = true,
                            IconeUrl = "/icons/camiseta.png",
                            Nome = "Camiseta Branca",
                            PrecoCentavos = 4990,
                            SetorId = new Guid("7f2ad0df-9ea1-4d0e-8cd7-fb5d714d4b01")
                        },
                        new
                        {
                            Id = new Guid("f0b3a91c-0ce7-40dd-9aa5-b3ad59f56076"),
                            Ativo = true,
                            IconeUrl = "/icons/calca.png",
                            Nome = "Calça Jeans Slim Azul",
                            PrecoCentavos = 13990,
                            SetorId = new Guid("7f2ad0df-9ea1-4d0e-8cd7-fb5d714d4b01")
                        },
                        new
                        {
                            Id = new Guid("c32eb407-794b-47e7-8b94-825349f4281e"),
                            Ativo = true,
                            IconeUrl = "/icons/jaqueta.png",
                            Nome = "Jaqueta Moletom Cinza",
                            PrecoCentavos = 18990,
                            SetorId = new Guid("7f2ad0df-9ea1-4d0e-8cd7-fb5d714d4b01")
                        },
                        new
                        {
                            Id = new Guid("7b6c4622-7d1e-4ea4-80c8-861ad9381abd"),
                            Ativo = true,
                            IconeUrl = "/icons/vestido.png",
                            Nome = "Vestido Floral",
                            PrecoCentavos = 15990,
                            SetorId = new Guid("f9fb24d3-7c2e-4b22-8a57-36262dd3cb84")
                        },
                        new
                        {
                            Id = new Guid("530f8d05-0b42-4838-8f47-2e9938c1570f"),
                            Ativo = true,
                            IconeUrl = "/icons/blusa.png",
                            Nome = "Blusa Seda Preta",
                            PrecoCentavos = 8990,
                            SetorId = new Guid("f9fb24d3-7c2e-4b22-8a57-36262dd3cb84")
                        },
                        new
                        {
                            Id = new Guid("f9a01a83-2a16-4e30-b728-13475a0e5ca4"),
                            Ativo = true,
                            IconeUrl = "/icons/saia.png",
                            Nome = "Saia Jeans",
                            PrecoCentavos = 11990,
                            SetorId = new Guid("f9fb24d3-7c2e-4b22-8a57-36262dd3cb84")
                        },
                        new
                        {
                            Id = new Guid("3565cc3a-652e-4b72-919d-58c81551979c"),
                            Ativo = true,
                            IconeUrl = "/icons/camiseta-infantil.png",
                            Nome = "Camiseta Super-Herói",
                            PrecoCentavos = 3990,
                            SetorId = new Guid("d214c62b-e16a-4b34-9d7a-5e2e2d98eabd")
                        },
                        new
                        {
                            Id = new Guid("c1a890d6-79ab-4df0-9fa5-dcdaf6c7d429"),
                            Ativo = true,
                            IconeUrl = "/icons/legging.png",
                            Nome = "Legging Rosa",
                            PrecoCentavos = 5990,
                            SetorId = new Guid("d214c62b-e16a-4b34-9d7a-5e2e2d98eabd")
                        },
                        new
                        {
                            Id = new Guid("7292e04f-74b6-4823-8c38-d2ff37b18d70"),
                            Ativo = true,
                            IconeUrl = "/icons/jaqueta-infantil.png",
                            Nome = "Jaqueta Jeans Infantil",
                            PrecoCentavos = 10990,
                            SetorId = new Guid("d214c62b-e16a-4b34-9d7a-5e2e2d98eabd")
                        },
                        new
                        {
                            Id = new Guid("ad208ef7-7c0e-4f41-bc49-e18cc26be3b9"),
                            Ativo = true,
                            IconeUrl = "/icons/bone.png",
                            Nome = "Boné Preto",
                            PrecoCentavos = 5990,
                            SetorId = new Guid("2a31e6a4-3e10-4c9b-bd14-752f2824c73f")
                        },
                        new
                        {
                            Id = new Guid("86ff2c54-3d52-4627-93d0-61aafb489a89"),
                            Ativo = true,
                            IconeUrl = "/icons/cinto.png",
                            Nome = "Cinto de Couro",
                            PrecoCentavos = 7990,
                            SetorId = new Guid("2a31e6a4-3e10-4c9b-bd14-752f2824c73f")
                        },
                        new
                        {
                            Id = new Guid("af0fdc59-5fd5-4cd1-a3bf-2cfdf5e2ddc9"),
                            Ativo = true,
                            IconeUrl = "/icons/mochila.png",
                            Nome = "Mochila Casual",
                            PrecoCentavos = 14990,
                            SetorId = new Guid("2a31e6a4-3e10-4c9b-bd14-752f2824c73f")
                        });
                });

            modelBuilder.Entity("Catalogo.Domain.Entities.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Setores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f2ad0df-9ea1-4d0e-8cd7-fb5d714d4b01"),
                            Ativo = true,
                            Nome = "Masculino",
                            Ordem = 1
                        },
                        new
                        {
                            Id = new Guid("f9fb24d3-7c2e-4b22-8a57-36262dd3cb84"),
                            Ativo = true,
                            Nome = "Feminino",
                            Ordem = 2
                        },
                        new
                        {
                            Id = new Guid("d214c62b-e16a-4b34-9d7a-5e2e2d98eabd"),
                            Ativo = true,
                            Nome = "Infantil",
                            Ordem = 3
                        },
                        new
                        {
                            Id = new Guid("2a31e6a4-3e10-4c9b-bd14-752f2824c73f"),
                            Ativo = true,
                            Nome = "Acessórios",
                            Ordem = 4
                        });
                });

            modelBuilder.Entity("Catalogo.Domain.Entities.Produto", b =>
                {
                    b.HasOne("Catalogo.Domain.Entities.Setor", "Setor")
                        .WithMany("Produtos")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Catalogo.Domain.Entities.Setor", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
