// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Reporting.Projections.Persistence;

#nullable disable

namespace Reporting.Projections.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20250929190000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Reporting.Projections.Entities.VendasPorDiaSetorView", b =>
            {
                b.Property<DateOnly>("Data")
                    .HasColumnType("date")
                    .HasConversion(
                        v => v.ToDateTime(TimeOnly.MinValue),
                        v => DateOnly.FromDateTime(v));

                b.Property<int>("QuantidadeItens")
                    .HasColumnType("int");

                b.Property<int>("QuantidadePedidos")
                    .HasColumnType("int");

                b.Property<Guid>("SetorId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("SetorNome")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int>("TotalVendidoCentavos")
                    .HasColumnType("int");

                b.HasKey("Data", "SetorId");

                b.ToTable("VendasPorDiaSetorView", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
